[workspace]
[package]
name = "TinkerVM"
version = "0.6.0-alpha.6"
edition = "2024"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 16
strip = "symbols"
incremental = true

[profile.dev]
opt-level = 0
lto = "thin"
codegen-units = 16
incremental = true

[dependencies]
thiserror = "~2.0.20"
dashmap = "~7.0.0-rc2"
